language: python
sudo: false
dist: bionic

python:
  - "3.8"

addons:
  apt:
    packages:
     - python3-pip
     - python3-dateutil
     - xsltproc

env:
  global:
   - GOPATH="${TRAVIS_BUILD_DIR}/.go_workspace"
   - mmark_src=github.com/miekg/mmark/mmark
   - mmark=./mmark

install:
 - pip3 install xml2rfc
 - if head -1 -q *.md | grep '^\-\-\-' >/dev/null 2>&1; then gem install --no-doc kramdown-rfc2629; fi
 - if head -1 -q *.md | grep '^%%%' >/dev/null 2>&1; then go get "$mmark_src" && go build "$mmark_src"; fi

script:
 - make
 - make issues || make issues DISABLE_ISSUE_FETCH=true && make gh-issues
 - make gh-pages

deploy:
  provider: script
  script: make upload
  skip_cleanup: true
  on:
    tags: true
